# Generated by Django 3.2.16 on 2023-11-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlansEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.CharField(max_length=128, verbose_name='Тип оборудования')),
                ('cost', models.IntegerField(verbose_name='Стоимость установки')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlansMonthlySub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(verbose_name='Стоимость месячной подписки')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlansOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('option', models.CharField(max_length=128, verbose_name='Опции связи')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlansPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('period', models.IntegerField(verbose_name='Период подписки')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlansTitleSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='Название тарифа')),
                ('speed', models.CharField(max_length=128, verbose_name='Скорость тарифа')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plansequipment')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plansoption')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plansperiod')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plansmonthlysub')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
