# Generated by Django 3.2.16 on 2023-11-20 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plansequipment',
            options={'verbose_name': 'Устанавливаемое оборудование', 'verbose_name_plural': 'Устанавливаемое оборудование'},
        ),
        migrations.AlterModelOptions(
            name='plansoption',
            options={'verbose_name': 'Опции связи', 'verbose_name_plural': 'Опции связи'},
        ),
        migrations.AlterModelOptions(
            name='plansperiod',
            options={'verbose_name': 'Период подписки', 'verbose_name_plural': 'Период подписок'},
        ),
        migrations.AlterModelOptions(
            name='planstitlespeed',
            options={'verbose_name': 'Описание тарифа', 'verbose_name_plural': 'Описание тарифов'},
        ),
        migrations.AlterField(
            model_name='planstitlespeed',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plansequipment', verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='planstitlespeed',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plansoption', verbose_name='Опция'),
        ),
        migrations.AlterField(
            model_name='planstitlespeed',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plansperiod', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='planstitlespeed',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Стоимость месячной подписки'),
        ),
        migrations.DeleteModel(
            name='PlansMonthlySub',
        ),
    ]
