# Generated by Django 5.0.1 on 2024-01-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='plans_icon/', verbose_name='Иконка'),
        ),
    ]
