# Generated by Django 3.2.16 on 2023-11-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20231121_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlansSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('speed', models.IntegerField(verbose_name='Скорость интернета')),
            ],
            options={
                'verbose_name': 'Скорость интернета',
                'verbose_name_plural': 'Скорость интернета',
            },
        ),
        migrations.AlterField(
            model_name='planstitlespeed',
            name='speed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plansspeed', verbose_name='Скорость интернета'),
        ),
    ]
