# Generated by Django 3.2.16 on 2023-11-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20231121_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='planstitlespeed',
            name='is_on_main',
            field=models.BooleanField(default=True, verbose_name='Отображение'),
        ),
    ]
