# Generated by Django 3.2.16 on 2023-11-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_planstitlespeed_is_on_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planstitlespeed',
            options={'ordering': ('price',), 'verbose_name': 'Описание тарифа', 'verbose_name_plural': 'Описание тарифов'},
        ),
    ]
