# Generated by Django 3.2.16 on 2023-12-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_planstitlespeed_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlansTitleSpeed',
            new_name='Plans',
        ),
    ]
