# Generated by Django 3.2.16 on 2023-12-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='../static_dev/img/default-avatar.jpg', null=True, storage='AVATAR_STORAGE', upload_to='', verbose_name='Аватар'),
        ),
    ]
