# Generated by Django 5.0.1 on 2024-01-10 19:34

import django.db.models.deletion
import personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='race',
            field=models.ForeignKey(default=personal.models.get_default_group, on_delete=django.db.models.deletion.SET_DEFAULT, to='auth.group'),
        ),
    ]
