# Generated by Django 5.0.1 on 2024-01-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="sex",
            field=models.CharField(
                choices=[("Муж.", "Man"), ("Жен.", "Woman"), ("Шрек", "Shrek")],
                default="Шрек",
                max_length=5,
                verbose_name="Пол",
            ),
        ),
    ]
