# Generated by Django 5.0.1 on 2024-01-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_customuser_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='race',
        ),
    ]
