# Generated by Django 5.0.1 on 2024-01-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0003_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="sex",
            field=models.CharField(
                choices=[("Муж.", "Мужчина"), ("Жен.", "Женщина"), ("Шрек", "Шрек")],
                default="Шрек",
                max_length=5,
                verbose_name="Пол",
            ),
        ),
    ]
