# Generated by Django 3.2.16 on 2024-01-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_customuser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='group',
        ),
    ]
